# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daqcs_pi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daqcs_pi.proto',
  package='daqcs_pi',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x64\x61qcs_pi.proto\x12\x08\x64\x61qcs_pi\"p\n\x04\x44\x61ta\x12\n\n\x02id\x18\x01 \x01(\x05\x12)\n\x0btempSensors\x18\x02 \x03(\x0b\x32\x14.daqcs_pi.TempSensor\x12\x31\n\x0fpressureSensors\x18\x03 \x03(\x0b\x32\x18.daqcs_pi.PressureSensor\"\'\n\nTempSensor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02\"+\n\x0ePressureSensor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='daqcs_pi.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='daqcs_pi.Data.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tempSensors', full_name='daqcs_pi.Data.tempSensors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pressureSensors', full_name='daqcs_pi.Data.pressureSensors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=140,
)


_TEMPSENSOR = _descriptor.Descriptor(
  name='TempSensor',
  full_name='daqcs_pi.TempSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='daqcs_pi.TempSensor.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='daqcs_pi.TempSensor.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=181,
)


_PRESSURESENSOR = _descriptor.Descriptor(
  name='PressureSensor',
  full_name='daqcs_pi.PressureSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='daqcs_pi.PressureSensor.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='daqcs_pi.PressureSensor.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=226,
)

_DATA.fields_by_name['tempSensors'].message_type = _TEMPSENSOR
_DATA.fields_by_name['pressureSensors'].message_type = _PRESSURESENSOR
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['TempSensor'] = _TEMPSENSOR
DESCRIPTOR.message_types_by_name['PressureSensor'] = _PRESSURESENSOR

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'daqcs_pi_pb2'
  # @@protoc_insertion_point(class_scope:daqcs_pi.Data)
  ))
_sym_db.RegisterMessage(Data)

TempSensor = _reflection.GeneratedProtocolMessageType('TempSensor', (_message.Message,), dict(
  DESCRIPTOR = _TEMPSENSOR,
  __module__ = 'daqcs_pi_pb2'
  # @@protoc_insertion_point(class_scope:daqcs_pi.TempSensor)
  ))
_sym_db.RegisterMessage(TempSensor)

PressureSensor = _reflection.GeneratedProtocolMessageType('PressureSensor', (_message.Message,), dict(
  DESCRIPTOR = _PRESSURESENSOR,
  __module__ = 'daqcs_pi_pb2'
  # @@protoc_insertion_point(class_scope:daqcs_pi.PressureSensor)
  ))
_sym_db.RegisterMessage(PressureSensor)


# @@protoc_insertion_point(module_scope)
